package com.daymooc.fcms.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSensitiveWords<M extends BaseSensitiveWords<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setWord(java.lang.String word) {
		set("word", word);
	}

	public java.lang.String getWord() {
		return get("word");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setWordPinyin(java.lang.String wordPinyin) {
		set("word_pinyin", wordPinyin);
	}

	public java.lang.String getWordPinyin() {
		return get("word_pinyin");
	}

}
