package com.daymooc.fcms.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUsersOpenOauth<M extends BaseUsersOpenOauth<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setAccessToken(java.lang.String accessToken) {
		set("access_token", accessToken);
	}

	public java.lang.String getAccessToken() {
		return get("access_token");
	}

	public void setExpireIn(java.lang.String expireIn) {
		set("expire_in", expireIn);
	}

	public java.lang.String getExpireIn() {
		return get("expire_in");
	}

	public void setOauthCode(java.lang.String oauthCode) {
		set("oauth_code", oauthCode);
	}

	public java.lang.String getOauthCode() {
		return get("oauth_code");
	}

	public void setOauthType(java.lang.Integer oauthType) {
		set("oauth_type", oauthType);
	}

	public java.lang.Integer getOauthType() {
		return get("oauth_type");
	}

	public void setOauthUserId(java.lang.String oauthUserId) {
		set("oauth_user_id", oauthUserId);
	}

	public java.lang.String getOauthUserId() {
		return get("oauth_user_id");
	}

	public void setRefreshToken(java.lang.String refreshToken) {
		set("refresh_token", refreshToken);
	}

	public java.lang.String getRefreshToken() {
		return get("refresh_token");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}

	public java.lang.Long getUserId() {
		return get("user_id");
	}

}
