package com.daymooc.fcms.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTags<M extends BaseTags<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setPosts(java.lang.Integer posts) {
		set("posts", posts);
	}

	public java.lang.Integer getPosts() {
		return get("posts");
	}

	public void setLocked(java.lang.Integer locked) {
		set("locked", locked);
	}

	public java.lang.Integer getLocked() {
		return get("locked");
	}

}
