package com.daymooc.fcms.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUploadCounter<M extends BaseUploadCounter<M>> extends Model<M> implements IBean {

	public void setUploadType(java.lang.String uploadType) {
		set("uploadType", uploadType);
	}

	public java.lang.String getUploadType() {
		return get("uploadType");
	}

	public void setCounter(java.lang.Integer counter) {
		set("counter", counter);
	}

	public java.lang.Integer getCounter() {
		return get("counter");
	}

	public void setDescr(java.lang.String descr) {
		set("descr", descr);
	}

	public java.lang.String getDescr() {
		return get("descr");
	}

}
