package com.daymooc.fcms.common.model;

import com.daymooc.fcms.common.model.base.BaseArticleType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArticleType extends BaseArticleType<ArticleType> {
	public static final ArticleType dao = new ArticleType().dao();
}
