package com.daymooc.fcms.common.model;

import com.daymooc.fcms.common.model.base.BaseLikeMessageLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LikeMessageLog extends BaseLikeMessageLog<LikeMessageLog> {
	public static final LikeMessageLog dao = new LikeMessageLog().dao();
}
