package com.daymooc.fcms.common.model;

import com.daymooc.fcms.common.model.base.BaseLoginLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LoginLog extends BaseLoginLog<LoginLog> {
	public static final LoginLog dao = new LoginLog().dao();
}
