package com.daymooc.fcms.common.model;

import com.daymooc.fcms.common.model.base.BaseMessage;
import com.daymooc.fcms.common.safe.JsoupFilter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Message extends BaseMessage<Message> {
	public static final Message dao = new Message().dao();
	
	public static final int TYPE_NORMAL = 0;    // 普通消息
	public static final int TYPE_SYSTEM = 1;    // 系统消息
	
	/**
	 * 过滤 title content 字段的 html 标记，防止 XSS 攻击
	 * 将回车换行转换成 <br> 标记便于 html 中显示换行
	 */
	protected void filter(int filterBy) {
	    String content = getContent().trim().replaceAll("\r\n", "<br>").replaceAll("\n", "<br>").replaceAll("\r", "<br>");
	    content = JsoupFilter.filterArticleContent(content);
	    setContent(content);
	}
}
