package com.daymooc.fcms.common.model;

import com.daymooc.fcms.common.model.base.BaseNewsFeed;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NewsFeed extends BaseNewsFeed<NewsFeed> {
	public static final NewsFeed dao = new NewsFeed().dao();
	
	public static final int REF_TYPE_POSTS = 1;//文章动态
	public static final int REF_TYPE_POSTS_COMMENTS = 2;//评论动态
	public static final int REF_TYPE_POSTS_COMMENTS_REPLY = 3;//评论回复动态
	
	public boolean isRefTypePosts()
	{
		return getRefType() == REF_TYPE_POSTS;
	}
	
	public boolean isRefTypePostsComments()
	{
		return getRefType() == REF_TYPE_POSTS_COMMENTS;
	}
	
	public boolean isRefTypePostsCommentsReply()
	{
		return getRefType() == REF_TYPE_POSTS_COMMENTS_REPLY;
	}

}
