package com.daymooc.fcms.common.model;

import com.daymooc.fcms.common.model.base.BasePostType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PostType extends BasePostType<PostType> {
	public static final PostType dao = new PostType().dao();
}
