package com.daymooc.fcms.common.model;

import com.daymooc.fcms.common.model.base.BasePostsComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PostsComment extends BasePostsComment<PostsComment> {
	public static final PostsComment dao = new PostsComment().dao();
}
