package com.daymooc.fcms.common.model;

import com.daymooc.fcms.common.model.base.BasePosts;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Posts extends BasePosts<Posts>
{
	public static final Posts dao =new Posts().dao();
	//public static final Posts	dao				= new Posts().dao();

	public static final int		ARTICLE			= 1;				// 文章
	public static final int		VIDEO			= 2;				// 视频
	public static final int		IMAGE			= 3;				// 图片
	public static final int		QUESTION		= 4;				// 问题

	public static final int		STATUS_PUB		= 0;				// 发布
	public static final int		STATUS_DRAFT	= 1;				// 草稿
	public static final int		STATUS_LOCK		= 2;				// 锁定
}
