package com.daymooc.fcms.common.model;

import com.daymooc.fcms.common.model.base.BasePostsLike;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PostsLike extends BasePostsLike<PostsLike> {
	public static final PostsLike dao = new PostsLike().dao();
}
