package com.daymooc.fcms.common.model;

import com.daymooc.fcms.common.model.base.BaseRemind;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Remind extends BaseRemind<Remind> {
	public static final Remind dao = new Remind().dao();
	
	// 提醒类型
	public static final int TYPE_REFER_ME = 0;      // 非数据库字段，仅用于在业务层判断所操作的类型，@我
    public static final int TYPE_MESSAGE = 1;       // 非数据库字段，仅用于在业务层判断所操作的类型，消息
    public static final int TYPE_FANS = 2;          // 非数据库字段，仅用于在业务层判断所操作的类型，粉丝关注消息
}
